# --- SERVER ---
server.port=9999

# --- DATASOURCE ---
spring.datasource.url=jdbc:postgresql://localhost:5432/netology?user=postgres&password=228488432

# --- JPA / HIBERNATE ---
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.use_sql_comments=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=false

# --- LIQUIBASE ---
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# --- MAIN ---
spring.main.allow-circular-references=true

# --- MULTIPART FILES ---
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# --- JWT CONFIG ---
jwt.token.secret=secret
jwt.token.expiration=180000

# --- CORS ---
cors.origins=http://localhost:8080
cors.methods=*
cors.headers=*
cors.credentials=true

# --- LOGGING FOR HIBERNATE ---
logging.level.root=WARN
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql=TRACE
